### ISSUE TITLE
update-gene2product.py not working

### ISSUE THREAD

**Issue by DrPintoThe2nd** [nextgenusfs/gene2product#13]
Hi Jon,

Per usual, thank you for all your work on this software. Truly amazing!
I recently annotated an invertebrate using v1.5.0 and thought I'd submit a few new gene product names. Sorry in advance, as I am not really a python person:

I forked the repository and tried to update, "python update-gene2product.py Gene2Products.new-names-passed.txt" and hit this error:
'''
Traceback (most recent call last):
File "update-gene2product.py", line 22, in <module> for line in db:
io.UnsupportedOperation: not readable 
'''

I worked around this (and the next error) by adding "a+" to lines 22 and 43, then I ran into this error and I don't know what it wants...

'''
"Traceback (most recent call last): 
File "update-gene2product.py", line 65, in <module>
os.rename(os.path.join(currentdir, 'ncbi_cleaned_gene_products.txt'), os.path.join(currentdir, 'ncbi_cleaned_gene_products.v'+version+'.txt'))
TypeError: can only concatenate str (not "NoneType") to str "
'''

I've attached my list of gene names in hopes that, if nothing else, someone can update the list for me.

[Gene2Products.new-names-passed.txt](https://github.com/nextgenusfs/gene2product/files/5287008/Gene2Products.new-names-passed.txt)

Cheers!
-bjp

**Comment by nextgenusfs** [comment]
Ok thanks for reporting -- I'll add these terms and look into the issues with the script.  Appreciate you contributing!

**Comment by nextgenusfs** [comment]
I think should be fixed now for next time, you can run a git pull on your fork and should get the updated script.  The last PR someone added append to the file opens which wasn't correct -- which I think is why it wasn't working in python 3.
