### ISSUE TITLE
Adding entries

### ISSUE THREAD

**Issue by aberaslop** [nextgenusfs/gene2product#14]
Hi Jon,

I'd like to contribute to this community project. I was testing the waters with the Gene2Products.new-names-passed.txt files from one of my genomes. 
I have already run update-gene2product.py. I have forked the repository, and now...how do I proceed? Should I just open a new pull request and add the new ncbi_cleaned_gene_products.txt file? I am very new at the inner guts of GitHub. 

Thanks!

**Comment by nextgenusfs** [comment]
Would be great to get the additions.  So first step would be to fork this repository to your user profile.  Then git commit your updated NCBI_cleaned_gene_products.txt file to your fork, and then you can do a pull request against the master repository which will pull in the updates.

**Comment by hyphaltip** [comment]
@aberaslop a pull request will let us interleave the new changes though I suspect it is drifted some in last year so you might need to re-generate or share the diff here
