### ISSUE TITLE
Adding terms

### ISSUE THREAD

**Issue by hyphaltip** [nextgenusfs/gene2product#2]
A little unclear how you would best like changes added -here is report from a recent run - these need the gene/protein name removed I assume:
```
#Name	Original Description	Cleaned Description	Error-message
CTS2	Inherit from sordNOG: Glycoside hydrolase  18 protein	Cts2p	Product defline failed funannotate checks
MUC21	Inherit from spriNOG: mucin 21, cell surface associated	Muc21p	Product defline failed funannotate checks
SLC3A1	Solute carrier  3 (Cystine, dibasic and neutral amino acid transporters, activator of cystine, dibasic and neutral amino acid transport), member 1	Slc3a1p	Product defline failed funannotate checks
```

**Comment by nextgenusfs** [comment]
So this is from the 'need-curating.txt' file, correct?  So you can modify these entries to something that would pass, i.e. 
```
#Name	Original Description	Cleaned Description	Error-message
CTS2	Glycoside hydrolase protein  Cts2p	Product defline failed funannotate checks
MUC21	cell surface associated mucin 21 Muc21p	Product defline failed funannotate checks
SLC3A1	amino acid transport protein  Slc3a1p  Product defline failed funannotate checks
```
And then these curated models can get passed back to funannotate annotate
```
funannotate annotate -i folder --fix need-curating.txt
```
Any names/products that are not in the Genes2Products database then show up in the `.new-names.passed.txt` file in the `annotate_results` folder.  That text file can be incorporated into the Genes2Products database by running the script in the forked Gene2Products repository. The resulting text file `ncbi_cleaned_gene_products.txt` can then be submitted as a PR.
```
update-gene2product.py Gene2Products.new-names-passed.txt
```

**Comment by hyphaltip** [comment]
This seems like it taken care of. it is ~4 years old issue I think we moved ahead in this time

**Comment by bpeacock44** [comment]
Hi @nextgenusfs I read over this an the linked above issue as I'm preparing to submit curations from my funannotate runs, but I just wanted to clarify something. I see that the --fix option file should have ID, name, and product for each of the "needs curation" genes.

In my Gene2Products.need-curating.txt file I have this: 
VWA7    coreceptor activity involved in Wnt signaling pathway, planar cell polarity pathway     Vwa7p   Product defline failed funannotate checks

I modify the description as follows:
VWA7    von Willebrand factor A domain-containing protein 7

Presumably this would be the name and product I should put in the --fix option. But what should I put for ID? Will it be genome-specific? If so, what if I have multiple versions of the same gene? e.g. in my gff3 file:

scaffold_5      funannotate     gene    31155   34239   .       +       .       ID=VZ033_000150;Name=VWA7_1;
scaffold_1630   funannotate     gene    2229    4713    .       +       .       ID=VZ033_011224;Name=VWA7_2;

**Comment by nextgenusfs** [comment]
So two ways to do it I think.  To do the one-time `--fix` in `funannotate annotate` you would generate your TSV file to look something like this: `--fix                Gene/Product names fixed (TSV: GeneID	Name	Product)`
```shell
VZ033_000150    VWA7_1   von Willebrand factor A domain-containing protein 7
VZ033_011224    VWA7_2   von Willebrand factor A domain-containing protein 7, variant 2
```
And then pass that file to --fix. 

The potentially better way would be to submit the "fixed" records to the gene2product database, then update your local database with the updated database and then re-run `funannotate annotate` -- theoretically it should fix those models properly.

**Comment by bpeacock44** [comment]
Ah, I understand. I was misunderstanding the purpose of curate. So it would be better to add this gene to the "Gene2Products.new-names-passed.txt file with an improved description, run update-gene2product.py and do a pull request, and then re-run once the pull request has been integrated?
