### ISSUE TITLE
kicked back products

### ISSUE THREAD

**Issue by hyphaltip** [nextgenusfs/gene2product#3]
This did not get flagged in tbl2asn but was kicked by NCBI upon submission.

hypothetical protein:
        4                            /product="Conserved protein (DUF2356)"
        6                            /product="DUF1900 super"
        4                            /product="Family with sequence similarity 49, member"
        4                            /product="Inherit from dotNOG: Snf7"
        2                            /product="Inherit from euNOG: HEAT repeat containing 2"
        2                            /product="protein of unknown function DUF3722"
        4                            /product="with sequence similarity 63, member B"
        6                            /product="with sequence similarity 72, member"

Suggests that these should be fixed:
INTS3	Conserved protein (DUF2356)
CRN1	DUF1900 super family
FAM49A	Family with sequence similarity 49, member
DID2	Inherit from dotNOG: Snf7
HEATR2	Inherit from euNOG: HEAT repeat containing 2
MDM10	protein of unknown function DUF3722
FAM63B	with sequence similarity 63, member B
FAM72A	with sequence similarity 72, member

Missing the word 'protein':
        2                            /product="Mitochondrial Translation Optimization"
MTO1	Mitochondrial Translation Optimization

CCDC97	Coiled-coil domain containing 97

Here's the mostly full list of what 

incomplete product name:
        2                            /product="ATPase, class V, type"

        16                           /product="chitin synthase, class"
CHS3	chitin synthase, class

Missing the word 'protein':
        2                            /product="Ataxin 2-like"
        2                            /product="Cation efflux"
        4                            /product="Chitinase domain containing 1"
        2                            /product="Coiled-coil domain containing 82"
        2                            /product="Coiled-coil domain containing 97"
        2                            /product="Coiled-coil domain containing"
        2                            /product="DDHD domain containing"
        4                            /product="DENN MADD domain containing"
        2                            /product="DNA repair"
        2                            /product="Dcp1-like decapping"
        4                            /product="ELMO CED-12 domain containing 2"
        2                            /product="Formin-like"
        2                            /product="Fungalysin/Thermolysin Propeptide Motif"
        2                            /product="G patch domain containing 2"
        2                            /product="G patch domain containing 8"
        2                            /product="G patch domain-containing protein 4"
        2                            /product="GRIP and coiled-coil domain containing 2"
        4                            /product="HEAT repeat containing 6"
        4                            /product="Isochorismatase domain containing 1"
        2                            /product="Kelch domain containing"
        4                            /product="MAD2 mitotic arrest deficient-like 2"
        2                            /product="MRNA capping" (note MRNA as well)
        2                            /product="Mitochondrial Distribution and Morphology"
        2                            /product="Mitochondrial Translation Optimization"
        4                            /product="Mitochondrial distribution and morphology
        8                            /product="Myb-like DNA-binding domain"
        6                            /product="Myb-like, SWIRM and MPN domains 1"
        2                            /product="Nuclear Envelope Morphology"
        2                            /product="PCI domain containing 2"
        6                            /product="PQ loop repeat"
        2                            /product="Plexin repeat"
        2                            /product="RNA binding"
        4                            /product="RWD domain containing 1"
        4                            /product="Run and fyve domain containing"
        2                            /product="RuvB-like 1"
        2                            /product="RuvB-like 2"
        4                            /product="SAM domain and HD"
        4                            /product="SET and MYND domain containing 3"
        8                            /product="SET domain containing 4"
        2                            /product="SRP40, C-terminal domain"
        4                            /product="Sad1 and UNC84 domain containing"
        4                            /product="THUMP domain containing 1"
        4                            /product="Thioredoxin-like 4A"
        4                            /product="WD domain, G-beta repeat"
        2                            /product="WD repeat and FYVE domain containing 3"
        4                            /product="WD repeat domain 12"
        4                            /product="WD repeat domain 33"
        4                            /product="WD repeat domain 4"
        8                            /product="WD repeat domain 43"
        6                            /product="WD repeat domain 81"
        2                            /product="WD repeat domain 87"
        4                            /product="Zinc finger, CCHC domain containing"
        4                            /product="Zinc finger, DHHC-type containing"
        8                            /product="adenyl nucleotide binding"
        2                            /product="cell division cycle 34"
        2                            /product="chromosome X 26"
        2                            /product="cingulin-like 1"
        2                            /product="coiled-coil and C2 domain containing"
        2                            /product="coiled-coil domain containing 64"
        4                            /product="complexed with cef1p"
        2                            /product="erv26 super"
        10                           /product="grainyhead-like"
        2                            /product="guanylyl cyclase domain containing 1"
        2                            /product="heme binding"
        8                            /product="intercellular trafficking and secretion"
        2                            /product="intracellular distribution of mitochondria"
        2                            /product="jumonji domain containing 6"
        4                            /product="mRNA turnover 4"
        2                            /product="membrane metallo-endopeptidase-like 1"
        4                            /product="metallophosphoesterase domain containing 1"
        2                            /product="methyltransferase like 5"
        8                            /product="mitochondrial"
        2                            /product="nuclear control of ATPase"
        6                            /product="oxidation resistance"
        2                            /product="p53 and DNA-damage regulated 1"
        2                            /product="peptidyl-tRNA hydrolase domain containing 1"
        6                            /product="piwi-like"
        6                            /product="ring finger and SPRY domain containing 1"
        2                            /product="sister chromatid cohesion"
        2                            /product="spermatoproteinsis associated 5"
        4                            /product="tetratricopeptide repeat domain 39A"
        2                            /product="tetratricopeptide repeat domain"
        2                            /product="tetratricopeptide repeat"
        4                            /product="transmembrane and coiled-coil domains 7"
        2                            /product="von Willebrand factor A domain-containing
        4                            /product="wD repeat domain"
        2                            /product="zinc finger, DHHC domain containing 11"
        8                            /product="zinc finger, DHHC-type containing 20"

hypothetical protein:
        2                            /product="Conserved protein (DUF2356)"
        2                            /product="DUF1900 super"
        2                            /product="Family with sequence similarity 49, member"
        2                            /product="Inherit from dotNOG: Snf7"
        4                            /product="Inherit from euNOG: HEAT repeat containing 2"
        4                            /product="protein of unknown function DUF3722"
        2                            /product="with sequence similarity 63, member A"
        6                            /product="with sequence similarity 72, member"

**Comment by nextgenusfs** [comment]
Added you to this repo so you can make changes and don't have to wait for me to merge something. So I guess the question I have is these ones that are missing "protein" from their name - is this missing from the original or did funannotate alter these names incorrectly?  I think this might not be the easiest question to answer, as right now the product names are stored in a dictionary after parsing SwissProt and then EggNog are added to that dictionary. 

So I just pushed a commit on funannotate that will output the raw names/product to a text file (I also added a "source" modifier so that you know where it came from).  These data are then fed into the method starting around here:
https://github.com/nextgenusfs/funannotate/blob/f0b37df5edadfd4980114c451f17f02c80be9d2d/bin/funannotate-functional.py#L661.  

I can see a few different solutions: 1) update code to catch/fix parsing errors, 2) add curated product definitions for these gene names to gene2product database, 3) probably we will have to do a mixture of the two. Parsing the names/definitions is difficult as the data continues to change as more things are added to UniProtKB/EggNog, etc. 

I'm about to board a plane coming to CA actually (two times this month!). But I will have some time again around 2 pm (PST) when I land in PSP.

**Comment by hyphaltip** [comment]
seems like we handled this. though I think some more systematic import of product names from NCBI approved list is needed
